In [1]:
import numpy as np
print (np.__version__)

2.4.3


- 데이터 분석 : 수치형 변수의 요약, 통계, 시각화
- 이미지 처리 : 이미지 데이터 사용
- 게임/시뮬레이션 : 구현을 위한 시뮬레이션 데이터 생성
- 머신러닝/딥러닝 : 금융, 의료, 실험, 센서 데이터 모두 np로 표현

In [6]:
arr = np.array([1, 2, 3, 4, 5])
print(arr, type(arr))  # [1 2 3 4 5]
arr.shape

[1 2 3 4 5] <class 'numpy.ndarray'>


(5,)

In [5]:
arr = np.array([[1, 2, 3],
                [4, 5, 6]])

print("합계:", arr.sum())          # 21
print("평균:", arr.mean())         # 3.5
print("표준편차:", arr.std())      # 1.707825127659933
print("행 방향 합계:", arr.sum(axis=1))  # [6 15]
print("열 방향 평균:", arr.mean(axis=0))  # [2.5 3.5 4.5]
arr.shape

합계: 21
평균: 3.5
표준편차: 1.707825127659933
행 방향 합계: [ 6 15]
열 방향 평균: [2.5 3.5 4.5]


(2, 3)

In [9]:
arr_3d = np.array([
    [[1, 2, 3], [1, 2, 3]], # 첫 번째 면 (2행 3열)
    [[4, 5, 6], [4, 5, 6]]  # 두 번째 면 (2행 3열)
])

print(arr_3d.shape)

(2, 2, 3)


In [12]:
arr_1 = np.array([10,10])
arr_1.shape

(2,)

In [13]:
arr_matrix = np.array([[10,10], [15,15]])
arr_matrix.shape

(2, 2)

In [14]:
arr_3d = np.array([[[1,5,9],[2,6,10]],[[3,7,11],[4,8,12]]])
arr_3d.shape

(2, 2, 3)

In [15]:
np.array([7]).shape, np.array([7]).ndim

((1,), 1)

In [17]:
 np.array([7]).ndim

1

In [19]:
arr1 = np.array([1, 2, 3, 4, 5]) #arr1.shape : (5,0)
arr12 = np.array([
    [1, 2, 3, 4, 5],
    [6, 7, 8, 9, 10]
]) 
arr12.shape, arr1.shape

((2, 5), (5,))

In [32]:
# (3,5) 행렬 arr13 만들기
arr13 = np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]])
arr13.shape

(3, 5)

In [30]:
arg13 = np.arange(1,16)
arg13

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [31]:
arg13.reshape(3,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [33]:
# 2행 3열의 랜덤 값 배열 (0~1 사이)
random_arr = np.random.rand(2, 3) 
random_arr

array([[0.43688074, 0.24161738, 0.447022  ],
       [0.63488903, 0.48014598, 0.8953525 ]])

In [34]:
random_arr.shape

(2, 3)

In [35]:
arr.dtype

dtype('int64')

In [36]:
# 데이터 타입 변환 예제
float_arr = np.array([1.1, 2.2, 3.3])
int_arr = float_arr.astype(np.int32)  # 실수를 정수로 변환
print("변환 전:", float_arr, float_arr.dtype)
print("변환 후:", int_arr, int_arr.dtype)

변환 전: [1.1 2.2 3.3] float64
변환 후: [1 2 3] int32


In [37]:
arr_str = np.array(['1', '2', 'three'])  # 'three'는 숫자로 변환 불가
arr_int = arr_str.astype(int)  # 오류 발생

ValueError: invalid literal for int() with base 10: np.str_('three')

In [38]:
arr_str = np.array(['1', '2', 'three']) 
arr_str.dtype

dtype('<U5')

In [44]:
# 1차원 배열 생성
a = np.arange(12)
print(a)  # [ 0  1  2  3  4  5  6  7  8  9 10 11]

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [45]:
# 2차원 배열로 변환 (3x4)
b = a.reshape(3, 4)
print(b)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [47]:
c = a.reshape(2,2,3)
c

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

In [48]:
# 1. 제품 A, B, C의 생산량 데이터를 담은 리스트 생성
# 각 내부 리스트는 [1일차, 2일차, 3일차] 생산량을 의미한다고 가정합니다.
production_data = [
    [100, 120, 110],  # 제품 A
    [90, 95, 100],    # 제품 B
    [150, 140, 160]   # 제품 C
]

# 2. 넘파이 배열(3x3)로 변환
arr_production = np.array(production_data)

# 3. 결과 확인
print("생산량 배열:")
print(arr_production)

print("\n배열의 형태(Shape):", arr_production.shape)

생산량 배열:
[[100 120 110]
 [ 90  95 100]
 [150 140 160]]

배열의 형태(Shape): (3, 3)


In [63]:
# 데이터 정의 (3행 3열: 제품 A, B, C / 1, 2, 3일차)
arr_production = np.array([
    [100, 120, 110, 140],  # 제품 A
    [90, 95, 100, 110],    # 제품 B
    [150, 140, 160, 130]   # 제품 C
])

# 1. 모든 데이터의 전체 합계
total_sum = np.sum(arr_production)

# 2. 제품별 합계 (행 방향 합계)
product_sum = np.sum(arr_production, axis=1)

# 3. 날짜별 합계 (열 방향 합계)
daily_sum = np.sum(arr_production, axis=0)

# 결과 출력
print(f"1. 전체 생산량 합계: {total_sum}")
print("-" * 30)
print(f"2. 제품별(A, B, C) 총 생산량: {product_sum}")
print(f"3. 날짜별(1, 2, 3일차) 총 생산량: {daily_sum}")

1. 전체 생산량 합계: 1445
------------------------------
2. 제품별(A, B, C) 총 생산량: [470 395 580]
3. 날짜별(1, 2, 3일차) 총 생산량: [340 355 370 380]


In [51]:
np.sum(production_data, axis=1)

array([330, 285, 450])

In [64]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
print(arr + 2)  # [3, 4, 5, 6, 7]
print(arr * 3)  # [3, 6, 9, 12, 15]
print(2 ** arr)  # [2, 4, 8, 16, 32]

[3 4 5 6 7]
[ 3  6  9 12 15]
[ 2  4  8 16 32]


In [65]:
sum(arr), sum(arr +2), sum(arr * 3)

(np.int64(15), np.int64(25), np.int64(45))

In [66]:
# 생산량 * 단가(이익률) = 총매출(총이익)
# sum(arr * 단가(이익률)) = 총매출(총이익)

In [70]:
arr_profit_per = ([20,30,25])
arr_profit_per

[20, 30, 25]

In [72]:
arr_production

array([[100, 120, 110, 140],
       [ 90,  95, 100, 110],
       [150, 140, 160, 130]])

In [77]:
sum(arr_production, axis=1)

TypeError: 'axis' is an invalid keyword argument for sum()

In [78]:
total_arr_production = np.sum(arr_production, axis=1)
total_arr_production

array([470, 395, 580])

In [80]:
total_sales = total_arr_production * profit_per_unit
total_sales

array([ 9400, 11850, 14500])